### ISSUE TITLE
Module and Starport powered off bug

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#925] opened 2024-02-02 20:47 UTC
Module and Starport even after powered off they can still produce units and the time to produce units isn't reduced when there's multiple of them

**Comment by Mailaender** [comment] 2024-02-02 21:00
Duplicate of https://github.com/OpenHV/OpenHV/issues/920?

**Comment by WilliamWeberBerrutti** [comment] 2024-02-02 21:21
No it isn't a duplicate. You can check by building 4 Modules or Starports. Set primary buildings for them. Try power off each of the primary ones and see if you can still produce from them and check if the production time of units is reduced or not.

**Closed** 2024-02-12 18:49 UTC
