### ISSUE TITLE
Scouts can spawn out of the map and making them unselectable if players don't use Select All Combat Units

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1124] opened 2024-08-05 21:54 UTC
![Screenshot_20240805_164648](https://github.com/user-attachments/assets/a77d1259-716b-451b-b3da-6079772139f6)

**Comment by Mailaender** [comment] 2024-08-05 22:16
Are they really out of the map or just on the map edge?

**Comment by WilliamWeberBerrutti** [comment] 2024-08-05 22:43
Now that you mentioned, it seems it's on the edge.

**Comment by Mailaender** [comment] 2024-08-06 12:01
Duplicate of https://github.com/OpenHV/OpenHV/issues/555

**Closed by Mailaender** 2024-08-06 12:01 UTC
Labels: polish
