### ISSUE TITLE
Locomotor.UpdateCellBlocking: Attempted to get trait from destroyed object

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#602] opened 2022-10-24 18:41 UTC
Exit code is 1. I have no idea how to reproduce this.
```
Platform is Linux
Engine version is 3f106bef72dc60a99d268eb864903a63fa2be684
Runtime: .NET CLR 6.0.9
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20220918)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
Loading mod: hv
[2022-10-24T14:45:40] Game started
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (drone 2820 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.Locomotor.UpdateCellBlocking(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/Locomotor.cs:line 488
   at OpenRA.Mods.Common.Traits.Locomotor.CanStayInCell(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/Locomotor.cs:line 287
   at OpenRA.Mods.Common.Traits.MobileInfo.CanStayInCell(World world, CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Mobile.cs:line 141
   at OpenRA.Mods.Common.Activities.MoveWithinRange.<CandidateMovementCells>b__8_0(CPos c) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs:line 54
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs:line 122
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 108
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 123
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs:line 102
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by Mailaender** [comment] 2022-10-25 14:57
Can you share the replay?

**Comment by nmoskopp** [comment] 2022-10-25 17:00
I have not found the replay, but did find another crash: https://github.com/OpenHV/OpenHV/issues/604

**Comment by nmoskopp** [comment] 2022-10-25 17:26
I created a replay that crashes OpenHV with the following output:
```
Platform is Linux
Engine version is 3f106bef72dc60a99d268eb864903a63fa2be684
Runtime: .NET CLR 6.0.9
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20220918)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
Loading mod: hv
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (drone 114 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.Locomotor.UpdateCellBlocking(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/Locomotor.cs:line 488
   at OpenRA.Mods.Common.Traits.Locomotor.CanMoveFreelyInto(Actor actor, CPos cell, SubCell subCell, BlockedByActor check, Actor ignoreActor) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/Locomotor.cs:line 230
   at OpenRA.Mods.Common.Pathfinder.DensePathGraph.GetConnections(CPos position) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/DensePathGraph.cs:line 131
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 219
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 290
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 865
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass15_0.<.ctor>b__0(BlockedByActor check) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 78
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 108
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 123
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by nmoskopp** [comment] 2022-10-25 17:27
Where are the replays located in the filesystem?

**Comment by Mailaender** [comment] 2022-10-25 20:16
`~/.config/openra/Replays/hv/`

How did you trigger the crash?

**Comment by nmoskopp** [comment] 2022-10-25 22:38
> How did you trigger the crash?

I sent drone ships to attack and nuked the drone ships while the drones were in the air.

**Comment by nmoskopp** [comment] 2022-10-26 10:01
[hv-2022-10-25T171949Z.orarep.zip](https://github.com/OpenHV/OpenHV/files/9868374/hv-2022-10-25T171949Z.orarep.zip)

**Comment by Mailaender** [comment] 2022-10-30 10:19
When I kill the drone ship all drones just die.

**Comment by Mailaender** [comment] 2022-10-30 14:58
According to https://github.com/OpenRA/OpenRA/issues/20370 to reproduce the drones have to die and respawn and die again. Seems to be resolved by https://github.com/OpenRA/OpenRA/pull/20401.

**Closed by Mailaender** 2022-10-30 14:58 UTC
Labels: crash
