### ISSUE TITLE
OpenHV-20220918-x86_64.AppImage crashes when pressing escape in a replay

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#604] opened 2022-10-25 16:59 UTC
This looks a lot like https://github.com/OpenHV/OpenHV/issues/603 – but is 100% reproducible in singleplayer mode.
```
Platform is Linux
Engine version is 3f106bef72dc60a99d268eb864903a63fa2be684
Runtime: .NET CLR 6.0.9
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20220918)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
Loading mod: hv
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.CheckboxWidget.Draw() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/CheckboxWidget.cs:line 88
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 479
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs:line 233
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Game.RenderTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 733
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 841
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by Mailaender** [comment] 2022-10-25 17:07
Duplicate of https://github.com/OpenHV/OpenHV/issues/603

**Closed by Mailaender** 2022-10-25 17:07 UTC
