### ISSUE TITLE
Make resource deposits finite

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#618] opened 2022-10-31 12:27 UTC
AFAIK resource deployments are practically infinite right now. IMO, it would give OpenHV more strategic depth if resources could run out during a typical OpenHV session.

In case you are interested how this can improve gameplay, try the RTS game Liberation Circuit. It has a resource placement mechanic similar to OpenHV (a few large deposits), but since resources can run out during the course of a normal game session, players are motivated to be more aggressive in the late game. It also results in more meaningful choices in the late game, since spamming units is rarely practical on a constrained budget.

I expect finite resource deployments to improve OpenHV gameplay in the following ways:

* Players would have a reason to redeploy a miner that is not fleeing from an attack.
* Hacker pods and ore smelters might become viable options to earn money in the late game.
* Map creators would have the option of having few large deposits (like now) or many smaller deposits.

For backwards compatibility with existing maps, an unset resource capacity could simply default to a very high finite capacity.

**Comment by GraionDilach** [comment] 2022-10-31 13:16
They are already finite. Exhausted mines only grant 10% of the deliveries, a system derived from RA3 (this is because there's no alternative secondary economies, and when a map fully runs out of resources, there's no way to break a stalemate, this ensures that there's still a way to provide some opportunity areas to break the stalemate).

**Comment by nmoskopp** [comment] 2022-10-31 13:19
OpenHV has both hacker pods and ore smelters, are those not secondaries in the sense you mean it?

How do I see how much a resource has left?

**Comment by GraionDilach** [comment] 2022-10-31 14:01
Ah, I was unaware of the hacker pods (this was probably added, after I mostly stopped contributing). Although it's faction-exclusive (so does Ore Smelter but the two aren't even comparable atm). This definitely needs a review.

Yes, the UI exposure of the deposit state etc. should be better.

**Comment by Mailaender** [comment] 2022-10-31 18:42
Duplicate of https://github.com/OpenHV/OpenHV/issues/290. We already made several changes to the resource system in the current iteration of pre-releases. Having depleted but not finite resources was the result.

**Closed by Mailaender** 2022-10-31 18:42 UTC
Labels: balancing

**Comment by GraionDilach** [comment] 2022-10-31 19:24
Maybe we should introduce a text overlay on Mining Towers when selected to reveal the remaining amount available in a text format would help explaining the second bar for clarity.

Also, there are definitely some confusing parts here. Using Cloverfield for testing, the "Resources depleted" EVA report is triggered when an unharmed Tower's secondary bar reaches 50%. Blowing up this Tower and rebuilding it on the same now emptied spot resets the bar to 100% and the bar still decreases until it reaches a value near 5%. So a rebuilt-but-emptied-before tower has a bar which doesn't seem meaningful and starting to mining a deposit makes an invalid assumption on the amount of resources remaining.
